apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-db
spec:
  serviceName: demo-db
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
      - name: db
        image: registry.redhat.io/rhscl/postgresql-12-rhel7
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: demo
        - name: POSTGRESQL_PASSWORD
          value: demo123
        - name: POSTGRESQL_DATABASE
          value: demodb
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-sc
      resources:
        requests:
          storage: 5Gi